version: '3.9'

services:
  feeding_routines_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6100:5432
    networks:
      - feeding_routines_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  feeding_routines:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 6150:80
    networks:
      - feeding_routines_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
    depends_on:
      feeding_routines_db:
        condition: service_started

networks:
  feeding_routines_net:
    driver: bridge
    name: feeding_routines_net